version: '2'

services:
  api:
    container_name: api
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      - "MYSQL_DATABASE=outsidein"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_ROOT_HOST=%"
